// webapp-tauri/src/views/Settings.vue
<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { api } from '@/api/client'
import { loadI18n, t } from '@/api/i18n'
import { logs, refreshStatus, status } from '@/api/store'
import type { ArgDefinition } from '@/api/types'
import AppAside from '@/components/AppAside.vue'
import AppMenu from '@/components/AppMenu.vue'
import DynamicForm from '@/components/DynamicForm.vue'

const route = useRoute()
const router = useRouter()

const selectedTask = ref('')
const schema = ref<Record<string, Record<string, Record<string, ArgDefinition>>>>({})
const config = ref<Record<string, unknown>>({})
const activeInstance = computed(() => status.instances[0]?.name ?? 'alas')
const saving = ref(false)
/** Tasks whose page is 'tool' show a status view instead of the form */
const toolTasks = ref<Set<string>>(new Set())
const toolAlive = ref(false)
const toolKeepBottom = ref(true)
const toolLogEl = ref<HTMLElement | null>(null)

const isToolTask = computed(() => toolTasks.value.has(selectedTask.value))

async function loadTask(task: string) {
  selectedTask.value = task
  const { menu, args } = await api.schema('alas')
  for (const data of Object.values(menu)) {
    if (data.page === 'tool') {
      for (const name of data.tasks ?? []) {
        toolTasks.value.add(name)
      }
    }
  }
  schema.value = args
  config.value = await api.config(activeInstance.value)
}

async function refreshToolState() {
  if (isToolTask.value && activeInstance.value) {
    const sched = await api.scheduler(activeInstance.value)
    toolAlive.value = sched.alive
  }
}

async function toggleTool() {
  if (toolAlive.value) {
    await api.stop(activeInstance.value)
  } else {
    await api.run(activeInstance.value)
  }
  await refreshToolState()
}

/** Group names shown in the right navigator. */
const navigatorGroups = computed(() =>
  Object.keys(schema.value[selectedTask.value] ?? {}).filter((name) => name !== 'Storage'),
)

function scrollToGroup(name: string) {
  document.getElementById(`group-${name}`)?.scrollIntoView({ behavior: 'smooth', block: 'start' })
}

async function saveValue(path: string, value: unknown) {
  saving.value = true
  try {
    await api.saveConfig(activeInstance.value, { [path]: value })
    config.value = await api.config(activeInstance.value)
  } finally {
    saving.value = false
  }
}

function onAsideSelect(name: string) {
  if (name === 'Home') {
    router.push('/develop')
    return
  }
  if (name === 'Manage') {
    router.push('/manage')
    return
  }
  // instance: stay on the overview page
  router.push('/')
}

function onMenuTask(task: string) {
  router.replace({ path: '/settings', query: { task } })
}

onMounted(async () => {
  void loadI18n()
  await refreshStatus()
  const task = (route.query.task as string) || 'Alas'
  await loadTask(task)
  await refreshToolState()
})

watch(
  () => route.query.task,
  async (task) => {
    if (task && task !== selectedTask.value) {
      await loadTask(task as string)
      await refreshToolState()
    }
  },
)

// Auto-scroll the tool log view
watch(
  () => logs[activeInstance.value]?.length,
  () => {
    if (toolKeepBottom.value && toolLogEl.value) {
      toolLogEl.value.scrollTop = toolLogEl.value.scrollHeight
    }
  },
)
</script>

<template>
  <div class="settings">
    <AppAside :active="activeInstance" @select="onAsideSelect" />
    <AppMenu @overview="router.push('/')" @task="onMenuTask" />

    <div class="content">
      <h4 v-if="selectedTask">{{ t(`Task.${selectedTask}.name`) }}</h4>

      <!-- tool tasks: scheduler bar (top) + form + log (bottom) -->
      <div v-if="isToolTask" class="tool-view">
        <div class="tool-bar">
          <span class="col-title">{{ t('Gui.Overview.Scheduler') }}</span>
          <button
            class="btn btn-sm"
            :class="toolAlive ? 'btn-off' : 'btn-on'"
            @click="toggleTool"
          >
            {{ toolAlive ? t('Gui.Button.Stop') : t('Gui.Button.Start') }}
          </button>
          <span class="col-title ms-auto">{{ t('Gui.Overview.Log') }}</span>
          <button class="btn btn-sm btn-adaptive" @click="toolKeepBottom = !toolKeepBottom">
            {{ toolKeepBottom ? t('Gui.Button.ScrollON') : t('Gui.Button.ScrollOFF') }}
          </button>
        </div>

        <div v-for="(groupArgs, groupKey) in schema[selectedTask] ?? {}" :key="groupKey" class="group-card" :id="`group-${groupKey}`">
          <template v-if="groupKey !== 'Storage'">
            <div class="group-card-title">{{ t(`${groupKey}._info.name`) }}</div>
            <div v-if="t(`${groupKey}._info.help`) !== `${groupKey}._info.help`" class="group-card-help">
              {{ t(`${groupKey}._info.help`) }}
            </div>
            <hr class="hr-group" />
            <DynamicForm
              :args="groupArgs"
              :group="groupKey"
              :task="selectedTask"
              :config="config"
              @save="saveValue"
            />
          </template>
        </div>

        <pre ref="toolLogEl" class="tool-log"><code>{{ (logs[activeInstance] ?? []).join('\n') }}</code></pre>
      </div>

      <template v-else>
        <p v-if="selectedTask && t(`Task.${selectedTask}.help`) !== `Task.${selectedTask}.help`" class="text-muted">
          {{ t(`Task.${selectedTask}.help`) }}
        </p>
        <div v-for="(groupArgs, groupKey) in schema[selectedTask] ?? {}" :key="groupKey" class="group-card" :id="`group-${groupKey}`">
          <template v-if="groupKey !== 'Storage'">
            <div class="group-card-title">{{ t(`${groupKey}._info.name`) }}</div>
            <div v-if="t(`${groupKey}._info.help`) !== `${groupKey}._info.help`" class="group-card-help">
              {{ t(`${groupKey}._info.help`) }}
            </div>
            <hr class="hr-group" />
            <DynamicForm
              :args="groupArgs"
              :group="groupKey"
              :task="selectedTask"
              :config="config"
              @save="saveValue"
            />
          </template>
        </div>
        <span v-if="saving" class="saving-hint">saving...</span>
      </template>

      <!-- right navigator: group anchors -->
      <nav v-if="navigatorGroups.length" class="navigator">
        <button
          v-for="name in navigatorGroups"
          :key="name"
          class="btn btn-sm btn-navigator"
          @click="scrollToGroup(name)"
        >
          {{ t(`${name}._info.name`) }}
        </button>
      </nav>
    </div>
  </div>
</template>

<style scoped>
.settings {
  height: 100%;
  display: flex;
  overflow: hidden;
}
.content {
  flex-grow: 1;
  padding: 1rem;
  overflow-y: auto;
}
.saving-hint {
  font-size: 12px;
  color: #4cd07d;
}
.navigator {
  margin: 0.5rem 1rem;
  height: min-content;
  max-width: 15rem;
  flex-shrink: 0;
  overflow-y: auto;
}
.tool-status-card {
  margin-top: 0.6rem;
}
.tool-bar {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  margin: 0.3rem 0;
  padding: 0.6rem;
}
.tool-bar .col-title {
  font-size: 1.25rem;
}
.tool-log {
  flex-grow: 1;
  margin: 0.3rem 0;
  min-height: 160px;
  max-height: 40vh;
  overflow-y: auto;
  background: #16191d;
  color: #d4d9de;
  padding: 8px;
  font-size: 12px;
  border-radius: 4px;
  white-space: pre-wrap;
}
</style>

// webapp-tauri/src/views/Settings.svelte
﻿<script lang="ts">
  import { api } from '../api/client'
  import { loadI18n, t } from '../api/i18n.svelte'
  import { logs, refreshStatus, status } from '../api/store.svelte'
  import { push, replace, route } from '../router.svelte'
  import type { ArgDefinition } from '../api/types'
  import AppAside from '../components/AppAside.svelte'
  import AppMenu from '../components/AppMenu.svelte'
  import DynamicForm from '../components/DynamicForm.svelte'

  let selectedTask = $state('')
  let schema = $state<Record<string, Record<string, Record<string, ArgDefinition>>>>({})
  let config = $state<Record<string, unknown>>({})
  const activeInstance = $derived(status.instances[0]?.name ?? 'alas')
  let saving = $state(false)
  /** Tasks whose page is 'tool' show a status view instead of the form */
  let toolTasks = $state<Set<string>>(new Set())
  let toolAlive = $state(false)
  let toolKeepBottom = $state(true)
  let toolLogEl = $state<HTMLElement | null>(null)

  const isToolTask = $derived(toolTasks.has(selectedTask))

  async function loadTask(task: string) {
    selectedTask = task
    const { menu, args } = await api.schema('alas')
    const found = new Set(toolTasks)
    for (const data of Object.values(menu)) {
      if (data.page === 'tool') {
        for (const name of data.tasks ?? []) {
          found.add(name)
        }
      }
    }
    toolTasks = found
    schema = args
    config = await api.config(activeInstance)
  }

  async function refreshToolState() {
    if (isToolTask && activeInstance) {
      const sched = await api.scheduler(activeInstance)
      toolAlive = sched.alive
    }
  }

  async function toggleTool() {
    if (toolAlive) {
      await api.stop(activeInstance)
    } else {
      await api.run(activeInstance)
    }
    await refreshToolState()
  }

  /** Group names shown in the right navigator. */
  const navigatorGroups = $derived(
    Object.keys(schema[selectedTask] ?? {}).filter((name) => name !== 'Storage'),
  )

  function scrollToGroup(name: string) {
    document.getElementById(`group-${name}`)?.scrollIntoView({ behavior: 'smooth', block: 'start' })
  }

  async function saveValue(path: string, value: unknown) {
    saving = true
    try {
      await api.saveConfig(activeInstance, { [path]: value })
      config = await api.config(activeInstance)
    } finally {
      saving = false
    }
  }

  function onAsideSelect(name: string) {
    if (name === 'Home') {
      push('/develop')
      return
    }
    if (name === 'Manage') {
      push('/manage')
      return
    }
    push('/')
  }

  function onMenuTask(task: string) {
    replace('/settings', { task })
  }

  $effect(() => {
    const task = route.query.task || 'Alas'
    if (task !== selectedTask || Object.keys(schema).length === 0) {
      void loadTask(task).then(() => refreshToolState())
    }
  })

  $effect(() => {
    void loadI18n()
    void refreshStatus()
  })

  // Auto-scroll the tool log view
  $effect(() => {
    void logs[activeInstance]?.length
    if (toolKeepBottom && toolLogEl) {
      toolLogEl.scrollTop = toolLogEl.scrollHeight
    }
  })
</script>

<div class="settings-wrap">
  <AppAside active={activeInstance} onselect={onAsideSelect} />
  <AppMenu onoverview={() => push('/')} ontask={onMenuTask} />

  <div class="content">
    {#if isToolTask}
      <!-- tool tasks: scheduler bar (top) + form + log (bottom) -->
      <div class="tool-view">
        <div class="tool-bar">
          <span class="col-title">{t('Gui.Overview.Scheduler')}</span>
          <button
            class="btn btn-sm"
            class:btn-off={toolAlive}
            class:btn-on={!toolAlive}
            onclick={toggleTool}
          >
            {toolAlive ? t('Gui.Button.Stop') : t('Gui.Button.Start')}
          </button>
          <span class="col-title ms-auto">{t('Gui.Overview.Log')}</span>
          <button
            class="btn btn-sm btn-adaptive"
            onclick={() => (toolKeepBottom = !toolKeepBottom)}
          >
            {toolKeepBottom ? t('Gui.Button.ScrollON') : t('Gui.Button.ScrollOFF')}
          </button>
        </div>

        {#each Object.entries(schema[selectedTask] ?? {}) as [groupKey, groupArgs] (groupKey)}
          {#if groupKey !== 'Storage'}
            <div class="group-card" id={`group-${groupKey}`}>
              <div class="group-card-title">{t(`${groupKey}._info.name`)}</div>
              {#if t(`${groupKey}._info.help`) !== `${groupKey}._info.help`}
                <div class="group-card-help">{t(`${groupKey}._info.help`)}</div>
              {/if}
              <hr class="hr-group" />
              <DynamicForm
                args={groupArgs}
                group={groupKey}
                task={selectedTask}
                config={config}
                onsave={saveValue}
              />
            </div>
          {/if}
        {/each}

        <pre class="tool-log" bind:this={toolLogEl}><code>{(logs[activeInstance] ?? []).join('\n')}</code></pre>
      </div>
    {:else}
      {#if selectedTask && t(`Task.${selectedTask}.help`) !== `Task.${selectedTask}.help`}
        <p class="text-muted">{t(`Task.${selectedTask}.help`)}</p>
      {/if}
      {#each Object.entries(schema[selectedTask] ?? {}) as [groupKey, groupArgs] (groupKey)}
        {#if groupKey !== 'Storage'}
          <div class="group-card" id={`group-${groupKey}`}>
            <div class="group-card-title">{t(`${groupKey}._info.name`)}</div>
            {#if t(`${groupKey}._info.help`) !== `${groupKey}._info.help`}
              <div class="group-card-help">{t(`${groupKey}._info.help`)}</div>
            {/if}
            <hr class="hr-group" />
            <DynamicForm
              args={groupArgs}
              group={groupKey}
              task={selectedTask}
              config={config}
              onsave={saveValue}
            />
          </div>
        {/if}
      {/each}
      {#if saving}
        <span class="saving-hint">saving...</span>
      {/if}
    {/if}
  </div>

  <!-- right navigator: group anchors -->
  {#if navigatorGroups.length}
    <nav class="navigator">
      {#each navigatorGroups as name (name)}
        <button class="btn btn-sm btn-navigator" onclick={() => scrollToGroup(name)}>
          {t(`${name}._info.name`)}
        </button>
      {/each}
    </nav>
  {/if}
</div>

<style>
  .settings-wrap {
    height: 100%;
    display: flex;
    overflow: hidden;
  }
  .content {
    flex: 1 1 auto;
    min-width: 0;
    padding: 1rem;
    overflow-y: auto;
  }
  .tool-bar {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    margin: 0.3rem 0;
    padding: 0.6rem;
  }
  .tool-bar .col-title {
    font-size: 1.25rem;
  }
  .tool-log {
    flex-grow: 1;
    margin: 0.3rem 0;
    min-height: 160px;
    max-height: 40vh;
    overflow-y: auto;
    background: #16191d;
    color: #d4d9de;
    padding: 8px;
    font-size: 12px;
    border-radius: 4px;
    white-space: pre-wrap;
  }
  .saving-hint {
    font-size: 12px;
    color: #4cd07d;
  }
  .navigator {
    margin: 0.5rem 1rem;
    height: min-content;
    width: max-content;
    min-width: 7rem;
    max-width: 15rem;
    flex-shrink: 0;
    overflow-y: auto;
  }
</style>
